// Tet -- http://tinyc.games -- (c) 2025 Jer Wilson
//
// Tet is tiny implementation of a fully-featured Tetris clone.

#ifndef TET_C_INCLUDED
#define TET_C_INCLUDED

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#define TINYC_DIR ".."
#include "build-config.h" // generated by CMake from build-config.h.in

#define SDL_DISABLE_IMMINTRIN_H // why do I need this again? For mac? For win??
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
#include <SDL3/SDL_vulkan.h>
#include "../common/tinyc.games/vulkan/main.c"

#define STBI_NO_SIMD
#define STB_IMAGE_IMPLEMENTATION
#include "../common/nothings/stb_image.h"

// compile as a single translation unit
#include "../common/tinyc.games/utils.c"
#include "../common/tinyc.games/audio.c"
#include "../common/tinyc.games/font.c"
#include "defs.c"
#include "graphics.c"
#include "input.c"

int get_interval()
{
        static int then = 0;
        int now = SDL_GetTicks();
        int diff = now - then;
        then = now;
        return diff;
}

// the entry point and main game loop
int main()
{
        setup();
        float accum_msec = 0.f;
        for (;;)
        {
                accum_msec += (float)get_interval();

                if (accum_msec < 7.3333f)
                        SDL_Delay(8 - (int)accum_msec);

                do_events();

                accum_msec += (float)get_interval();
                for (; accum_msec > 8.3333f; accum_msec -= 8.3333f)
                {
                        update_player();
                        accum_msec += (float)get_interval();
                }

                draw_start();
                draw_player();
                draw_menu();
                draw_end();
                vulkan_submit();

                tick++;
        }
}

void do_events()
{
        while (SDL_PollEvent(&event)) switch (event.type)
        {
                case SDL_EVENT_QUIT:                exit(0);
                case SDL_EVENT_KEY_DOWN:            key_down();       break;
                case SDL_EVENT_KEY_UP:              key_up();         break;
                case SDL_EVENT_GAMEPAD_BUTTON_DOWN: btn_down();       break;
                case SDL_EVENT_GAMEPAD_BUTTON_UP:   btn_up();         break;

                case SDL_EVENT_GAMEPAD_ADDED:       gamepad_add();    break;
                case SDL_EVENT_GAMEPAD_REMOVED:     gamepad_remove(); break;

                case SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED:
                        vulkan_recreate_swapchain();
                        resize(event.window.data1, event.window.data2);
                        break;
        }
}

// initial setup to get the window and rendering going
void setup()
{
        srand(time(NULL));
        p = play;
        SDL_Init(SDL_INIT_VIDEO | SDL_INIT_GAMEPAD | SDL_INIT_AUDIO);
        SDL_SetGamepadEventsEnabled(true);

        vulkan_startup("Tet", TINYC_DIR "/common/tinyc.games/vulkan/assets/tinyc-icon.png",
                        TINYC_DIR "/tet-game/shaders/", win_x, win_y);
        win = vk.window;
        vk.clear_color = (VkClearColorValue){{0.18f, 0.18f, 0.18f, 1.f}};

        SDL_GetWindowSizeInPixels(win, &win_x, &win_y);
        resize(win_x, win_y);
        audio_init();
        font_init();
        draw_setup();
}

void kill_lines()
{
        p->lines += p->shiny_lines;
        p->level = p->lines / 10;
        p->reward = combo_bonus[MIN(MAX_COMBO, p->combo)] * rewards[p->shiny_lines];
        p->combo++;
        if (p->tspin == TSPIN_FULL)
                p->reward *= 2;
        p->score += p->reward;
        p->shiny_lines = 0;

        // clean up sliced pieces
        for (int y = 0; y < BHEIGHT; y++)
        {
                p->row[y].offset = 0;

                if (y > 0 && p->row[y - 1].fullness == 10)
                        for (int x = 0; x < BWIDTH; x++)
                                p->row[y].col[x].part &= ~1;

                if (y < BHEIGHT - 1 && p->row[y + 1].fullness == 10)
                        for (int x = 0; x < BWIDTH; x++)
                                p->row[y].col[x].part &= ~4;
        }

        for (int y = 0; y < BHEIGHT; y++)
        {
                if (p->row[y].fullness != 10) continue;

                if (p->combo > 2)
                {
                        p->crash_row = y;
                        p->crash_time = 1000;
                }

                for (int j = y; j > 0; j--)
                {
                        p->row[j] = p->row[j - 1];
                        p->row[j].offset += bs;
                }

                memset(&p->row[0], 0, sizeof p->row[0]);
        }
}

void new_game()
{
        memset(p->row, 0, sizeof p->row);
        p->bag_idx = BAG_SZ;
        if (p->best < p->score) p->best = p->score;
        p->score = 0;
        p->lines = 0;
        p->level = 0;
        p->held.color = 0;
        p->hold_uses = 0;
        p->countdown_time = 4 * CTDN_TICKS;
}

// set the current piece to the top, middle to start falling
void reset_fall()
{
        p->idle_time = 0;
        p->grounded_moves = 0;
        p->it.x = 3;
        p->it.y = 3;
        p->it.rot = 0;
}

// pick a new next piece from the bag, and put the old one in play
void new_piece()
{
        if (p->bag_idx >= BAG_SZ) // need to make a new bag?
        {
                p->bag_idx = 0;

                for (int i = 0; i < BAG_SZ; i++)
                        p->bag[i] = i % 7 + 1;

                for (int i = 0; i < BAG_SZ; i++)
                        SWAP(p->bag[i], p->bag[rand() % BAG_SZ]);
        }

        p->it.color = p->next[0];
        memmove(p->next, p->next + 1, sizeof *(p->next) * 4);
        p->next[4] = p->bag[p->bag_idx++];
        reset_fall();
}

//move the falling piece left, right, or down
void move(int dx, int dy, int gravity)
{
        if (!gravity)
                p->move_cooldown = p->move_cooldown ? 8 : 18;

        int collision = collide(p->it.x + dx, p->it.y + dy, p->it.rot);

        if (collision == NONE)
        {
                p->it.x += dx;
                p->it.y += dy;

                // reset idle time if you voluntarily move DOWN
                if (dy) p->idle_time = 0;

                // remember last successful x movement time
                if (dx) p->last_dx_tick = tick;

                // reset idle time if piece is grounded, limit grounded moves though
                if (p->grounded && p->grounded_moves < 15)
                {
                        p->idle_time = 0;
                        p->grounded_moves++;
                }

                if (!gravity)
                        audio_tone(TRIANGLE, C3, F3, 1, 1, 1, 1);
        }
        else if (dy && gravity)
        {
                bake();
                if (tick != p->beam_tick)
                        audio_tone(TRIANGLE, C4, F4, 10, 10, 10, 10);
        }
        else if (collision == WALL)
        {
                if (dx == -1 && tick - p->last_dx_tick < 16)
                {
                        p->shake_x -= .25f;
                        audio_tone(TRIANGLE, C2, C2, 25, 5, 5, 25);
                }
                if (dx ==  1 && tick - p->last_dx_tick < 16)
                {
                        p->shake_x += .25f;
                        audio_tone(TRIANGLE, E2, C2, 15, 5, 5, 15);
                }
        }
}

// update everything related to current player, while the game is running normally
void update_player()
{
        if (state != PLAY) return;

        if (p->countdown_time > 0)
        {
                int note = p->countdown_time > CTDN_TICKS ? A4 : A5;
                if (p->countdown_time % CTDN_TICKS == 0)
                        audio_tone(TRIANGLE, note, note, 80, 50, 5, 20);

                if (--p->countdown_time > CTDN_TICKS)
                        return;
        }

        if (p->crash_time > 0) p->crash_time--;

        p->ticks++;

        while (!p->it.color && !p->shine_time && !p->dead_time)
                new_piece();

        p->grounded = collide(p->it.x, p->it.y + 1, p->it.rot);

        if (p->move_cooldown) p->move_cooldown--;
        if (p->move_cooldown < 2)
        {
                if (p->left)  move(-1, 0, 0);
                if (p->right) move( 1, 0, 0);
                if (p->down)  move( 0, 1, 0);
        }

        for (int y = 0; y < BHEIGHT; y++)
                if (p->row[y].offset > 0)
                        p->row[y].offset = MAX(0, p->row[y].offset - bs4);
                else if (p->row[y].offset < 0)
                        p->row[y].offset = MIN(0, p->row[y].offset + bs4);

        if (p->shine_time > 0 && --p->shine_time == 0)
                kill_lines();

        if (p->dead_time > 0)
        {
                p->dead_time--;
                int x = p->dead_time % BWIDTH;
                int y = BHEIGHT - 1 - p->dead_time / BWIDTH;
                p->row[y].col[x].part = 0;
                if (p->dead_time == 0)
                        new_game();
        }

        if (++p->idle_time >= (p->grounded ? 100 : speeds[MIN(MAX_SPEED, p->level)]))
        {
                move(0, 1, 1);
                p->idle_time = 0;
        }

        // update shaky offsets
        if (p->shake_x < .01f && p->shake_x > -.01f) p->shake_x = .0f;
        if (p->shake_y < .01f && p->shake_y > -.01f) p->shake_y = .0f;
        if (p->shake_x) p-> shake_x *= .98f;
        if (p->shake_y) p-> shake_y *= .98f;
}

void game_over()
{
        memset(p->bag, 0, sizeof p->bag);
        memset(p->next, 0, sizeof p->next);
        p->dead_time = BHEIGHT * BWIDTH;
}

// check if a line has been completed and act accordingly
int increment_and_check_line(int y)
{
        if (++p->row[y].fullness != 10)
                return 0;

        p->reward = 0; // set up hovering reward number
        p->reward_x = p->board_x + bs * (p->it.x + 2);
        p->reward_y = p->board_y + bs * (p->it.y - 4);
        p->shine_time = 40;
        p->shiny_lines++;

        for (int i = 0; i < BWIDTH; i++)
                p->row[y].col[i].color = 8;
        return 1;
}

// bake the falling piece into the background/board
void bake()
{
        int completed_lines = 0;
        int tsum = 0; // for detecting t-spins
        int stuck = collide(p->it.x    , p->it.y - 1, p->it.rot)
                 && collide(p->it.x - 1, p->it.y    , p->it.rot)
                 && collide(p->it.x + 1, p->it.y    , p->it.rot);

        for (int i = 0; i < 4; i++) for (int j = 0; j < 4; j++)
        {
                int world_i = i + p->it.x;
                int world_j = j + p->it.y;
                int part = is_solid_part(p->it.color, p->it.rot, i, j);

                int tpart = is_tspin_part(p->it.color, p->it.rot, i, j);
                if (world_i < 0 || world_i >= BWIDTH || world_j < 0 || world_j >= BHEIGHT ||
                        p->row[world_j].col[world_i].color)
                        tsum += tpart;

                if (!part) continue;

                if (p->row[world_j].col[world_i].color)
                        game_over();

                p->row[world_j].col[world_i].color = p->it.color;
                p->row[world_j].col[world_i].part = part;
                completed_lines += increment_and_check_line(world_j);
        }

        p->it.color = 0;
        p->hold_uses = 0;
        p->tspin = TSPIN_NONE;

        if (stuck && tsum >= 21)
        {
                p->tspin = TSPIN_FULL;
                audio_tone(SQUARE, F2, F2, 2, 2, 2, 2);
                audio_tone(SQUARE, D4, D4, 2, 3, 1, 1);
                audio_tone(SINE, C5, C5, 20, 5, 1, 1);
                audio_tone(SINE, E5, E5, 80, 5, 1, 40);
        }
        else if (stuck && tsum == 12)
        {
                p->tspin = TSPIN_MINI;
                audio_tone(SQUARE, F2, F2, 2, 2, 2, 2);
                audio_tone(SQUARE, D4, D4, 2, 3, 1, 1);
        }
        else if (completed_lines)
        {
                for (int i = 0; i < completed_lines; i++)
                        audio_tone(SINE, G3, G5, 20, 50, 50, 200);
        }
        else
        {
                p->combo = 0; // break combo
        }
}

// check if a sub-part of the falling shape is solid at a particular rotation
int is_solid_part(int shape, int rot, int i, int j)
{
        int base = shape * 5 + rot * 5 * 8 * 4;
        int part = shapes[base + j * 5 * 8 + i];
        return part < '@' ? 0 : part;
}

int is_tspin_part(int shape, int rot, int i, int j)
{
        int base = shape * 5 + rot * 5 * 8 * 4;
        int part = shapes[base + j * 5 * 8 + i];
        return part == ',' ? 1 : part == ';' ? 10 : 0;
}

// check if the current piece would collide at a certain position and rotation
int collide(int x, int y, int rot)
{
        int ret = NONE;
        for (int i = 0; i < 4; i++) for (int j = 0; j < 4; j++)
                if (is_solid_part(p->it.color, rot, i, j))
                {
                        if (i + x < 0 || i + x >= BWIDTH || j + y >= BHEIGHT)
                                return WALL;
                        if (p->row[j + y].col[i + x].color)
                                ret = NORMAL;
                }

        return ret;
}

#endif // TET_C_INCLUDED
