#ifndef VULKAN_DEMO_MAIN_C
#define VULKAN_DEMO_MAIN_C

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <limits.h>
#include <time.h>
#include <math.h>
#include <assert.h>

#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
#include <SDL3/SDL_vulkan.h>
#include <vulkan/vulkan.h>

#define STBI_NO_SIMD
#ifdef TINYC_VULKAN_TRIANGLE_MAIN
#define STB_IMAGE_IMPLEMENTATION
#endif
#include "../../nothings/stb_image.h"

// Directory holding the compiled .spv shaders. build-config.h (generated by
// CMake, include it before this file) overrides this with an absolute path,
// so games find their shaders even when the IDE runs them with a working
// directory other than the build root.
#ifndef TINYC_SPV_DIR
#define TINYC_SPV_DIR "shaders/"
#endif

// A failed Vulkan call usually leaves a garbage handle behind, and the
// crash (or hang, if a fence never signals) shows up somewhere far away.
// Dying loudly at the failing call is the kindest option.
#define VKCHECK(x) do { VkResult vkcheck_r = (x); if (vkcheck_r != VK_SUCCESS) { \
        fprintf(stderr, "%s:%d: %s failed (%d)\n", __FILE__, __LINE__, #x, vkcheck_r); \
        exit(-1); } } while (0)

#include "instance.c"
#include "physical.c"
#include "queue.c"
#include "device.c"
#include "surface.c"
#include "image.c"
#include "frame.c"
#include "shader.c"
#include "pipeline.c"
#include "command.c"
#include "synchronization.c"

struct vk {
        VkInstance instance;
        uint32_t physicalDeviceCount;
        VkPhysicalDevice *physicalDevices;
        uint32_t bestPhysicalDeviceIndex;
        VkPhysicalDevice *bestPhysicalDevice;
        uint32_t queueFamilyCount;
        VkQueueFamilyProperties *queueFamilyProperties;
        VkDevice device;
        uint32_t bestGraphicsQueueFamilyindex;
        VkQueue drawingQueue; // also the presenting queue
        SDL_Window *window;
        VkSurfaceKHR surface;
        VkSurfaceCapabilitiesKHR surfaceCapabilities;
        VkSurfaceFormatKHR bestSurfaceFormat;
        VkPresentModeKHR bestPresentMode;
        VkExtent2D bestSwapchainExtent;
        uint32_t imageArrayLayers;
        VkSwapchainKHR swapchain;
        uint32_t swapchainImageCount;
        VkImage *swapchainImages;
        VkImageView *swapchainImageViews;
        VkRenderPass renderPass;
        VkFramebuffer *framebuffers;
        VkCommandPool commandPool;
        VkCommandBuffer *commandBuffers;
        uint32_t maxFrames;
        VkSemaphore *waitSemaphores;
        VkSemaphore *signalSemaphores;
        VkFence *frontFences;
        VkFence *backFences;
        uint32_t imageIndex;
        uint32_t currentFrame;


        int pipelineCount;
        struct pipeline {
                VkPipelineLayout layout;
                VkPipeline pipeline;
                // Metadata for hot-reload
                char vert_src[256];  // GLSL source path (not .spv)
                char geom_src[256];
                char frag_src[256];
                SDL_Time vert_mtime;   // last modification time
                SDL_Time geom_mtime;
                SDL_Time frag_mtime;
                int bindingDescCount;
                int attributeDescCount;
                VkVertexInputBindingDescription bindingDescs[8];
                VkVertexInputAttributeDescription attributeDescs[16];
                VkDescriptorSetLayout *pDescriptorSetLayout;
                VkRenderPass renderPass;  // VK_NULL_HANDLE = use default
                int flags;
        } pipelines[100];

        // Depth buffer
        VkImage depthImage;
        VkDeviceMemory depthMemory;
        VkImageView depthImageView;

        // Shader source directory (for hot-reload)
        char shader_dir[256];

        VkClearColorValue clear_color;
} vk;

void vulkan_create_swapchain();
void vulkan_destroy_swapchain();
void vulkan_recreate_swapchain();

// screenshot support (defined below, used by vulkan_submit)
static int sshot_capture(VkImage src, const char *path);
static char sshot_pending_path[512];
static int sshot_pending;

void vulkan_startup(char *window_title, char *icon_file, char *shader_dir, int win_w, int win_h)
{
        SDL_Init(SDL_INIT_VIDEO);

        vk.clear_color = (VkClearColorValue){{0.0f, 0.2f, 0.8f, 0.0f}};

        // Store shader source directory for hot-reload
        if (shader_dir)
                snprintf(vk.shader_dir, sizeof(vk.shader_dir), "%s", shader_dir);
        else
                vk.shader_dir[0] = '\0';

        vk.instance = createInstance();

        vk.physicalDeviceCount = getPhysicalDeviceNumber(&vk.instance);
        if (vk.physicalDeviceCount == 0)
        {
                fprintf(stderr, "no Vulkan devices found - is a Vulkan driver installed?\n");
                exit(-1);
        }
        vk.physicalDevices = getPhysicalDevices(&vk.instance, vk.physicalDeviceCount);
        vk.bestPhysicalDeviceIndex = getBestPhysicalDeviceIndex(vk.physicalDevices, vk.physicalDeviceCount);
        vk.bestPhysicalDevice = &vk.physicalDevices[vk.bestPhysicalDeviceIndex];

        VkPhysicalDeviceMemoryProperties mem_props;
        vkGetPhysicalDeviceMemoryProperties(*vk.bestPhysicalDevice, &mem_props);

        for (uint32_t i = 0; i < mem_props.memoryHeapCount; i++) {
                if (mem_props.memoryHeaps[i].flags & VK_MEMORY_HEAP_DEVICE_LOCAL_BIT) {
                        fprintf(stderr, "Heap %d: Total VRAM: %llu MB\n", i,
                               (unsigned long long)(mem_props.memoryHeaps[i].size / (1024 * 1024)));
                }
        }

        // The window and surface come before device creation so the queue
        // family can be chosen with present support in mind.
        vk.window = createVulkanWindow(win_w, win_h, window_title, icon_file);
        vk.surface = createSurface(vk.window, &vk.instance);

        vk.queueFamilyCount = getQueueFamilyNumber(vk.bestPhysicalDevice);
        vk.queueFamilyProperties = getQueueFamilyProperties(vk.bestPhysicalDevice, vk.queueFamilyCount);
        vk.bestGraphicsQueueFamilyindex = getBestGraphicsQueueFamilyIndex(vk.bestPhysicalDevice, &vk.surface, vk.queueFamilyProperties, vk.queueFamilyCount);

        vk.device = createDevice(vk.bestPhysicalDevice, vk.bestGraphicsQueueFamilyindex);

        // Print GPU info for debugging
        VkPhysicalDeviceProperties deviceProps;
        vkGetPhysicalDeviceProperties(*vk.bestPhysicalDevice, &deviceProps);
        fprintf(stderr, "Vulkan GPU: %s (driver %u.%u.%u)\n", deviceProps.deviceName,
                VK_VERSION_MAJOR(deviceProps.driverVersion),
                VK_VERSION_MINOR(deviceProps.driverVersion),
                VK_VERSION_PATCH(deviceProps.driverVersion));
        fprintf(stderr, "Queue family %u: draw and present on one queue\n",
                vk.bestGraphicsQueueFamilyindex);

        vk.drawingQueue = getDrawingQueue(&vk.device, vk.bestGraphicsQueueFamilyindex);
        deleteQueueFamilyProperties(&vk.queueFamilyProperties);

        vk.bestSurfaceFormat = getBestSurfaceFormat(&vk.surface, vk.bestPhysicalDevice);
        vk.bestPresentMode = getBestPresentMode(&vk.surface, vk.bestPhysicalDevice);
        fprintf(stderr, "Present mode: %s\n",
                vk.bestPresentMode == VK_PRESENT_MODE_MAILBOX_KHR ? "MAILBOX" :
                vk.bestPresentMode == VK_PRESENT_MODE_FIFO_KHR ? "FIFO" :
                vk.bestPresentMode == VK_PRESENT_MODE_IMMEDIATE_KHR ? "IMMEDIATE" : "OTHER");
        vk.imageArrayLayers = 1;

        vk.renderPass = createRenderPass(&vk.device, &vk.bestSurfaceFormat);
        vk.commandPool = createCommandPool(&vk.device, vk.bestGraphicsQueueFamilyindex);

        vulkan_create_swapchain();

        vk.commandBuffers = createCommandBuffers(&vk.device, &vk.commandPool, vk.swapchainImageCount);

        // Per-FRAME objects (indexed by currentFrame): the acquire semaphore
        // and the fence that paces the CPU. Two frames in flight is the
        // conventional choice - the CPU can record one frame while the GPU
        // draws another; more would only add input latency.
        // Per-IMAGE objects (indexed by imageIndex): the render-finished
        // semaphore must belong to the image because presentation holds it
        // until that specific image comes back around.
        vk.maxFrames = 2;
        vk.waitSemaphores = createSemaphores(&vk.device, vk.maxFrames);
        vk.frontFences = createFences(&vk.device, vk.maxFrames);
        vk.signalSemaphores = createSemaphores(&vk.device, vk.swapchainImageCount);
        vk.backFences = createEmptyFences(vk.swapchainImageCount);
}

// Creates/recreates swapchain, depth buffer, and framebuffers
void vulkan_create_swapchain() {
        vk.surfaceCapabilities = getSurfaceCapabilities(&vk.surface, vk.bestPhysicalDevice);
        vk.bestSwapchainExtent = getBestSwapchainExtent(&vk.surfaceCapabilities, vk.window);

        vk.swapchain = createSwapchain(&vk.device, &vk.surface, &vk.surfaceCapabilities, &vk.bestSurfaceFormat, &vk.bestSwapchainExtent, &vk.bestPresentMode, vk.imageArrayLayers);

        vk.swapchainImageCount = getSwapchainImageNumber(&vk.device, &vk.swapchain);
        vk.swapchainImages = getSwapchainImages(&vk.device, &vk.swapchain, vk.swapchainImageCount);
        vk.swapchainImageViews = createImageViews(&vk.device, &vk.swapchainImages, &vk.bestSurfaceFormat, vk.swapchainImageCount, vk.imageArrayLayers);

        // Create depth buffer
        VkImageCreateInfo depthImageInfo = {
                .sType = VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO,
                .imageType = VK_IMAGE_TYPE_2D,
                .format = VK_FORMAT_D32_SFLOAT,
                .extent = { vk.bestSwapchainExtent.width, vk.bestSwapchainExtent.height, 1 },
                .mipLevels = 1,
                .arrayLayers = 1,
                .samples = VK_SAMPLE_COUNT_1_BIT,
                .tiling = VK_IMAGE_TILING_OPTIMAL,
                .usage = VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT,
                .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
                .initialLayout = VK_IMAGE_LAYOUT_UNDEFINED,
        };
        VKCHECK(vkCreateImage(vk.device, &depthImageInfo, NULL, &vk.depthImage));

        VkMemoryRequirements depthMemReqs;
        vkGetImageMemoryRequirements(vk.device, vk.depthImage, &depthMemReqs);

        // Prefer device-local memory, but any type the image accepts will work
        VkPhysicalDeviceMemoryProperties memProps;
        vkGetPhysicalDeviceMemoryProperties(*vk.bestPhysicalDevice, &memProps);
        uint32_t depthMemType = UINT32_MAX;
        for (uint32_t i = 0; i < memProps.memoryTypeCount; i++) {
                if ((depthMemReqs.memoryTypeBits & (1u << i)) &&
                    (memProps.memoryTypes[i].propertyFlags & VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT)) {
                        depthMemType = i;
                        break;
                }
        }
        if (depthMemType == UINT32_MAX)
                for (uint32_t i = 0; i < memProps.memoryTypeCount; i++)
                        if (depthMemReqs.memoryTypeBits & (1u << i)) {
                                depthMemType = i;
                                break;
                        }

        VkMemoryAllocateInfo depthAllocInfo = {
                .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
                .allocationSize = depthMemReqs.size,
                .memoryTypeIndex = depthMemType,
        };
        VKCHECK(vkAllocateMemory(vk.device, &depthAllocInfo, NULL, &vk.depthMemory));
        VKCHECK(vkBindImageMemory(vk.device, vk.depthImage, vk.depthMemory, 0));

        VkImageViewCreateInfo depthViewInfo = {
                .sType = VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO,
                .image = vk.depthImage,
                .viewType = VK_IMAGE_VIEW_TYPE_2D,
                .format = VK_FORMAT_D32_SFLOAT,
                .subresourceRange = {
                        .aspectMask = VK_IMAGE_ASPECT_DEPTH_BIT,
                        .baseMipLevel = 0,
                        .levelCount = 1,
                        .baseArrayLayer = 0,
                        .layerCount = 1,
                },
        };
        VKCHECK(vkCreateImageView(vk.device, &depthViewInfo, NULL, &vk.depthImageView));

        vk.framebuffers = createFramebuffers(&vk.device, &vk.renderPass, &vk.bestSwapchainExtent, &vk.swapchainImageViews, vk.swapchainImageCount, &vk.depthImageView);
}

void vulkan_destroy_swapchain() {
        deleteFramebuffers(&vk.device, &vk.framebuffers, vk.swapchainImageCount);
        deleteImageViews(&vk.device, &vk.swapchainImageViews, vk.swapchainImageCount);
        deleteSwapchainImages(&vk.swapchainImages);

        vkDestroyImageView(vk.device, vk.depthImageView, NULL);
        vkDestroyImage(vk.device, vk.depthImage, NULL);
        vkFreeMemory(vk.device, vk.depthMemory, NULL);

        deleteSwapchain(&vk.device, &vk.swapchain);
}

void vulkan_recreate_swapchain() {
        // Block while the window has zero drawable size (e.g. minimized) -
        // creating a 0-sized swapchain is invalid. PumpEvents keeps the OS
        // window state current without stealing events from the game's loop.
        int w = 0, h = 0;
        SDL_GetWindowSizeInPixels(vk.window, &w, &h);
        while (w == 0 || h == 0) {
                SDL_Delay(10);
                SDL_PumpEvents();
                SDL_GetWindowSizeInPixels(vk.window, &w, &h);
        }

        vkDeviceWaitIdle(vk.device);

        uint32_t oldImageCount = vk.swapchainImageCount;
        vulkan_destroy_swapchain();
        vulkan_create_swapchain();

        // The new swapchain may hand back a different number of images; the
        // command buffers and per-image sync objects are sized to that count,
        // so rebuild them when it changes. (The per-frame objects -
        // waitSemaphores and frontFences - are sized to maxFrames and
        // unaffected by the swapchain.)
        if (vk.swapchainImageCount != oldImageCount) {
                deleteCommandBuffers(&vk.device, vk.commandBuffers, &vk.commandPool, oldImageCount);
                deleteSemaphores(&vk.device, &vk.signalSemaphores, oldImageCount);
                deleteEmptyFences(&vk.backFences);

                vk.commandBuffers = createCommandBuffers(&vk.device, &vk.commandPool, vk.swapchainImageCount);
                vk.signalSemaphores = createSemaphores(&vk.device, vk.swapchainImageCount);
                vk.backFences = createEmptyFences(vk.swapchainImageCount);
        }

        fprintf(stderr, "Swapchain recreated: %dx%d\n", vk.bestSwapchainExtent.width, vk.bestSwapchainExtent.height);
}

// Get file modification time using SDL (cross-platform)
static SDL_Time get_file_mtime(const char *path) {
        SDL_PathInfo info;
        if (SDL_GetPathInfo(path, &info)) {
                return info.modify_time;
        }
        return 0;
}

// Build full source path from shader filename
// "sun.frag" -> "{shader_dir}sun.frag"
static void build_src_path(const char *filename, char *src, size_t src_size) {
        if (vk.shader_dir[0]) {
                snprintf(src, src_size, "%s%s", vk.shader_dir, filename);
        } else {
                snprintf(src, src_size, "%s", filename);
        }
}

// Filename portion of a shader path, or the whole string if it has no '/'.
// (strrchr(path,'/')+1 would dereference past NULL for a bare filename.)
static const char *shader_basename(const char *path) {
        const char *slash = strrchr(path, '/');
        return slash ? slash + 1 : path;
}

// Compile a GLSL shader to SPIR-V using glslangValidator
// Returns 0 on success, non-zero on failure
static int compile_shader(const char *src_path, const char *spv_path) {
        char cmd[1024];
        snprintf(cmd, sizeof(cmd), "glslangValidator --quiet -V \"%s\" -o \"%s\" 2>&1", src_path, spv_path);
        int ret = system(cmd);
        if (ret != 0) {
                fprintf(stderr, "Shader compile failed: %s\n", src_path);
                // Run again without --quiet to show errors
                snprintf(cmd, sizeof(cmd), "glslangValidator -V \"%s\" -o \"%s\"", src_path, spv_path);
                system(cmd);
        }
        return ret;
}

// Internal: create/recreate pipeline at given index using stored metadata.
// The new pipeline is built completely before the old one (if any) is
// destroyed, so a failed rebuild leaves the pipeline as it was - a shader
// hot-reload with a broken shader keeps rendering the previous version.
static int vulkan_create_pipeline_at(int index) {
        struct pipeline *p = &vk.pipelines[index];

        // Determine .spv paths from source paths
        char vert_spv[256], geom_spv[256], frag_spv[256];
        snprintf(vert_spv, sizeof(vert_spv), TINYC_SPV_DIR "%s.spv", shader_basename(p->vert_src));
        if (p->geom_src[0])
                snprintf(geom_spv, sizeof(geom_spv), TINYC_SPV_DIR "%s.spv", shader_basename(p->geom_src));
        snprintf(frag_spv, sizeof(frag_spv), TINYC_SPV_DIR "%s.spv", shader_basename(p->frag_src));

        uint32_t vertexShaderSize = 0;
        char *vertexShaderCode = getShaderCode(vert_spv, &vertexShaderSize);
        if (vertexShaderCode == NULL) {
                fprintf(stderr, "vertex shader %s not found\n", vert_spv);
                return -1;
        }
        VkShaderModule vertexShaderModule = createShaderModule(&vk.device, vertexShaderCode, vertexShaderSize);

        VkShaderModule geometryShaderModule = VK_NULL_HANDLE;
        char *geometryShaderCode = NULL;
        if (p->geom_src[0]) {
                uint32_t geometryShaderSize = 0;
                geometryShaderCode = getShaderCode(geom_spv, &geometryShaderSize);
                if (geometryShaderCode == NULL) {
                        fprintf(stderr, "geometry shader %s not found\n", geom_spv);
                        deleteShaderModule(&vk.device, &vertexShaderModule);
                        deleteShaderCode(&vertexShaderCode);
                        return -1;
                }
                geometryShaderModule = createShaderModule(&vk.device, geometryShaderCode, geometryShaderSize);
        }

        uint32_t fragmentShaderSize = 0;
        char *fragmentShaderCode = getShaderCode(frag_spv, &fragmentShaderSize);
        if (fragmentShaderCode == NULL) {
                fprintf(stderr, "fragment shader %s not found\n", frag_spv);
                if (geometryShaderModule) {
                        deleteShaderModule(&vk.device, &geometryShaderModule);
                        deleteShaderCode(&geometryShaderCode);
                }
                deleteShaderModule(&vk.device, &vertexShaderModule);
                deleteShaderCode(&vertexShaderCode);
                return -1;
        }
        VkShaderModule fragmentShaderModule = createShaderModule(&vk.device, fragmentShaderCode, fragmentShaderSize);

        VkPipelineLayout newLayout;
        if (p->pDescriptorSetLayout)
                newLayout = createPipelineLayoutWithDescriptors(&vk.device, p->pDescriptorSetLayout);
        else
                newLayout = createPipelineLayout(&vk.device);

        VkRenderPass rp = p->renderPass ? p->renderPass : vk.renderPass;
        VkPipeline newPipeline = createGraphicsPipeline(
                &vk.device,
                &newLayout,
                &vertexShaderModule,
                geometryShaderModule ? &geometryShaderModule : NULL,
                &fragmentShaderModule,
                &rp,
                &vk.bestSwapchainExtent,
                p->bindingDescCount,
                p->bindingDescs,
                p->attributeDescCount,
                p->attributeDescs,
                p->flags
        );

        deleteShaderModule(&vk.device, &fragmentShaderModule);
        deleteShaderCode(&fragmentShaderCode);
        if (geometryShaderModule) {
                deleteShaderModule(&vk.device, &geometryShaderModule);
                deleteShaderCode(&geometryShaderCode);
        }
        deleteShaderModule(&vk.device, &vertexShaderModule);
        deleteShaderCode(&vertexShaderCode);

        if (newPipeline == VK_NULL_HANDLE) {
                deletePipelineLayout(&vk.device, &newLayout);
                return -1;
        }

        // Success: replace the old pipeline (present only on reload)
        if (p->pipeline)
                deleteGraphicsPipeline(&vk.device, &p->pipeline);
        if (p->layout)
                deletePipelineLayout(&vk.device, &p->layout);
        p->pipeline = newPipeline;
        p->layout = newLayout;

        return 0;
}

// Reload a single pipeline by recompiling its shaders
int vulkan_reload_pipeline(int index) {
        if (index < 0 || index >= vk.pipelineCount) {
                fprintf(stderr, "Invalid pipeline index: %d\n", index);
                return -1;
        }

        struct pipeline *p = &vk.pipelines[index];

        // Determine .spv paths
        char vert_spv[256], geom_spv[256], frag_spv[256];
        snprintf(vert_spv, sizeof(vert_spv), TINYC_SPV_DIR "%s.spv", shader_basename(p->vert_src));
        if (p->geom_src[0])
                snprintf(geom_spv, sizeof(geom_spv), TINYC_SPV_DIR "%s.spv", shader_basename(p->geom_src));
        snprintf(frag_spv, sizeof(frag_spv), TINYC_SPV_DIR "%s.spv", shader_basename(p->frag_src));

        // Compile shaders
        if (compile_shader(p->vert_src, vert_spv) != 0) return -1;
        if (p->geom_src[0] && compile_shader(p->geom_src, geom_spv) != 0) return -1;
        if (compile_shader(p->frag_src, frag_spv) != 0) return -1;

        // Wait for the GPU to finish with the old pipeline, which
        // vulkan_create_pipeline_at destroys once the new one is ready
        vkDeviceWaitIdle(vk.device);

        int result = vulkan_create_pipeline_at(index);

        // Update mtimes on success
        if (result == 0) {
                p->vert_mtime = get_file_mtime(p->vert_src);
                p->geom_mtime = p->geom_src[0] ? get_file_mtime(p->geom_src) : 0;
                p->frag_mtime = get_file_mtime(p->frag_src);
        }

        return result;
}

// Check if a pipeline's shaders have changed
static int pipeline_shaders_changed(int index) {
        struct pipeline *p = &vk.pipelines[index];

        SDL_Time vert_now = get_file_mtime(p->vert_src);
        SDL_Time frag_now = get_file_mtime(p->frag_src);
        SDL_Time geom_now = p->geom_src[0] ? get_file_mtime(p->geom_src) : 0;

        return (vert_now != p->vert_mtime) ||
               (frag_now != p->frag_mtime) ||
               (geom_now != p->geom_mtime);
}

// Reload only pipelines whose shaders have changed
void vulkan_reload_all_pipelines() {
        int changed = 0, failed = 0;

        for (int i = 0; i < vk.pipelineCount; i++) {
                if (!pipeline_shaders_changed(i))
                        continue;

                changed++;
                if (vulkan_reload_pipeline(i) != 0) {
                        fprintf(stderr, "Pipeline %d: FAILED\n", i);
                        failed++;
                } else {
                        fprintf(stderr, "Pipeline %d: reloaded\n", i);
                }
        }

        if (changed == 0)
                fprintf(stderr, "No shader changes detected\n");
        else
                fprintf(stderr, "Reloaded %d/%d pipelines\n", changed - failed, changed);
}

// Internal: store pipeline metadata for hot-reload
static void store_pipeline_metadata(int index, char *vert, char *geom, char *frag,
        int bindingDescCount, VkVertexInputBindingDescription *bindingDescs,
        int attributeDescCount, VkVertexInputAttributeDescription *attributeDescs,
        VkDescriptorSetLayout *pDescriptorSetLayout,
        VkRenderPass renderPass,
        int flags
) {
        struct pipeline *p = &vk.pipelines[index];

        // Store full source paths
        build_src_path(vert, p->vert_src, sizeof(p->vert_src));
        if (geom)
                build_src_path(geom, p->geom_src, sizeof(p->geom_src));
        else
                p->geom_src[0] = '\0';
        build_src_path(frag, p->frag_src, sizeof(p->frag_src));

        // Record initial modification times
        p->vert_mtime = get_file_mtime(p->vert_src);
        p->geom_mtime = geom ? get_file_mtime(p->geom_src) : 0;
        p->frag_mtime = get_file_mtime(p->frag_src);

        // Store vertex input info
        p->bindingDescCount = bindingDescCount;
        p->attributeDescCount = attributeDescCount;
        if (bindingDescCount > 0 && bindingDescs)
                memcpy(p->bindingDescs, bindingDescs, bindingDescCount * sizeof(VkVertexInputBindingDescription));
        if (attributeDescCount > 0 && attributeDescs)
                memcpy(p->attributeDescs, attributeDescs, attributeDescCount * sizeof(VkVertexInputAttributeDescription));

        p->pDescriptorSetLayout = pDescriptorSetLayout;
        p->renderPass = renderPass;
        p->flags = flags;
}

// Note: pDescriptorSetLayout is kept (not copied) so shader hot-reload can
// rebuild the pipeline layout later - it must point to storage that stays
// valid for the life of the pipeline (the games pass globals).
int vulkan_make_pipeline(char *vert, char *geom, char *frag,
        int bindingDescCount, VkVertexInputBindingDescription *bindingDescs,
        int attributeDescCount, VkVertexInputAttributeDescription *attributeDescs,
        VkDescriptorSetLayout *pDescriptorSetLayout,
        VkRenderPass renderPass,
        int flags
) {
        assert(vk.pipelineCount < 100);
        int index = vk.pipelineCount;

        // Store metadata for hot-reload (VK_NULL_HANDLE for default render pass)
        store_pipeline_metadata(index, vert, geom, frag,
                bindingDescCount, bindingDescs, attributeDescCount, attributeDescs,
                pDescriptorSetLayout, renderPass, flags);

        // Create the pipeline
        if (vulkan_create_pipeline_at(index) != 0) {
                fprintf(stderr, "Failed to create pipeline %d\n", index);
                return -1;
        }

        return vk.pipelineCount++;
}

void vulkan_start_recording(uint32_t imageIndex)
{
        int i = imageIndex;

        VkCommandBufferBeginInfo commandBufferBeginInfo;
        VkRenderPassBeginInfo renderPassBeginInfo;
        VkRect2D renderArea = {
                {0, 0},
                {vk.bestSwapchainExtent.width, vk.bestSwapchainExtent.height}
        };
        VkClearValue clearValues[2] = {
                {.color = vk.clear_color},
                {.depthStencil = {1.0f, 0}}
        };

        commandBufferBeginInfo.sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO;
        commandBufferBeginInfo.pNext = NULL;
        commandBufferBeginInfo.flags = 0;
        commandBufferBeginInfo.pInheritanceInfo = NULL;

        renderPassBeginInfo.sType = VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO;
        renderPassBeginInfo.pNext = NULL;
        renderPassBeginInfo.renderPass = vk.renderPass;
        renderPassBeginInfo.framebuffer = vk.framebuffers[i];
        renderPassBeginInfo.renderArea = renderArea;
        renderPassBeginInfo.clearValueCount = 2;
        renderPassBeginInfo.pClearValues = clearValues;

        vkResetCommandBuffer(vk.commandBuffers[i], 0);
        VKCHECK(vkBeginCommandBuffer(vk.commandBuffers[i], &commandBufferBeginInfo));
        vkCmdBeginRenderPass(vk.commandBuffers[i], &renderPassBeginInfo, VK_SUBPASS_CONTENTS_INLINE);
}

void vulkan_finish_recording(uint32_t imageIndex)
{
        int i = imageIndex;
        vkCmdEndRenderPass(vk.commandBuffers[i]);
        VKCHECK(vkEndCommandBuffer(vk.commandBuffers[i]));
}

void vulkan_acquire_next()
{
        // Use currentFrame to select which semaphore to use for acquisition
        vkWaitForFences(vk.device, 1, &vk.frontFences[vk.currentFrame], VK_TRUE, UINT64_MAX);

        // A stale swapchain (resized/rotated) makes acquire fail with
        // OUT_OF_DATE; rebuild and try again. On OUT_OF_DATE the acquire
        // semaphore is left unsignaled, so it is safe to reuse on retry.
        VkResult result = vkAcquireNextImageKHR(vk.device, vk.swapchain, UINT64_MAX, vk.waitSemaphores[vk.currentFrame], VK_NULL_HANDLE, &vk.imageIndex);
        while (result == VK_ERROR_OUT_OF_DATE_KHR) {
                vulkan_recreate_swapchain();
                result = vkAcquireNextImageKHR(vk.device, vk.swapchain, UINT64_MAX, vk.waitSemaphores[vk.currentFrame], VK_NULL_HANDLE, &vk.imageIndex);
        }
        // SUBOPTIMAL still acquired an image (and signaled the semaphore), so
        // render this frame; present will recreate the swapchain. Anything
        // else (e.g. DEVICE_LOST) is unrecoverable.
        if (result != VK_SUCCESS && result != VK_SUBOPTIMAL_KHR) {
                fprintf(stderr, "vkAcquireNextImageKHR failed (%d)\n", result);
                exit(-1);
        }

        // Wait for any previous work on this specific image to complete
        if(vk.backFences[vk.imageIndex] != VK_NULL_HANDLE){
                vkWaitForFences(vk.device, 1, &vk.backFences[vk.imageIndex], VK_TRUE, UINT64_MAX);
        }

        vulkan_start_recording(vk.imageIndex);
}

void vulkan_submit()
{
        vulkan_finish_recording(vk.imageIndex);

        VkPipelineStageFlags pipelineStage = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
        VkSubmitInfo submitInfo = {
                VK_STRUCTURE_TYPE_SUBMIT_INFO,
                NULL,
                1,
                &vk.waitSemaphores[vk.currentFrame],
                &pipelineStage,
                1,
                &vk.commandBuffers[vk.imageIndex],
                1,
                &vk.signalSemaphores[vk.imageIndex]  // Use imageIndex for signal semaphore
        };
        vkResetFences(vk.device, 1, &vk.frontFences[vk.currentFrame]);
        // An unchecked failed submit would leave the fence forever unsignaled
        // and the next vkWaitForFences would hang with no diagnostics
        VKCHECK(vkQueueSubmit(vk.drawingQueue, 1, &submitInfo, vk.frontFences[vk.currentFrame]));

        // Track which fence is now associated with this image
        vk.backFences[vk.imageIndex] = vk.frontFences[vk.currentFrame];

        // Screenshot this frame before presenting, while its image is still
        // acquired (reading a presented image is not spec-clean). Wait for the
        // draw to finish, copy, then present - a one-frame stall, debug only.
        if (sshot_pending)
        {
                vkWaitForFences(vk.device, 1, &vk.frontFences[vk.currentFrame], VK_TRUE, UINT64_MAX);
                sshot_capture(vk.swapchainImages[vk.imageIndex], sshot_pending_path);
                sshot_pending = 0;
        }

        VkPresentInfoKHR presentInfo = {
                VK_STRUCTURE_TYPE_PRESENT_INFO_KHR,
                NULL,
                1,
                &vk.signalSemaphores[vk.imageIndex],  // Use imageIndex for present
                1,
                &vk.swapchain,
                &vk.imageIndex,
                NULL
        };
        VkResult result = vkQueuePresentKHR(vk.drawingQueue, &presentInfo);
        if (result == VK_ERROR_OUT_OF_DATE_KHR || result == VK_SUBOPTIMAL_KHR)
                vulkan_recreate_swapchain();

        vk.currentFrame = (vk.currentFrame + 1) % vk.maxFrames;
}

// ---- screenshot: read the last presented swapchain image back to a PNG ----
//
// A self-contained PNG encoder (no libpng/zlib): the pixel data is wrapped in
// a zlib stream of uncompressed DEFLATE "stored" blocks, so the only maths
// needed are CRC-32 (per chunk) and Adler-32 (the zlib trailer). Fine for a
// debug screenshot - the file is a touch bigger than a compressed PNG but
// opens in anything.

static uint32_t sshot_crc_table[256];
static int sshot_crc_ready;

static uint32_t sshot_crc(uint32_t crc, const uint8_t *buf, size_t len)
{
        if (!sshot_crc_ready) {
                for (uint32_t n = 0; n < 256; n++) {
                        uint32_t c = n;
                        for (int k = 0; k < 8; k++)
                                c = (c & 1) ? 0xEDB88320u ^ (c >> 1) : (c >> 1);
                        sshot_crc_table[n] = c;
                }
                sshot_crc_ready = 1;
        }
        for (size_t i = 0; i < len; i++)
                crc = sshot_crc_table[(crc ^ buf[i]) & 0xff] ^ (crc >> 8);
        return crc;
}

static void sshot_be32(FILE *f, uint32_t v)
{
        uint8_t b[4] = { v >> 24, v >> 16, v >> 8, v };
        fwrite(b, 1, 4, f);
}

static void sshot_chunk(FILE *f, const char *type, const uint8_t *data, uint32_t len)
{
        sshot_be32(f, len);
        fwrite(type, 1, 4, f);
        if (len) fwrite(data, 1, len, f);
        uint32_t crc = sshot_crc(0xffffffffu, (const uint8_t *)type, 4);
        crc = sshot_crc(crc, data, len);
        sshot_be32(f, crc ^ 0xffffffffu);
}

// write w*h RGB (3 bytes/pixel) as a PNG; returns 0 on success
static int sshot_write_png(const char *path, const uint8_t *rgb, uint32_t w, uint32_t h)
{
        FILE *f = fopen(path, "wb");
        if (!f) return -1;

        static const uint8_t sig[8] = { 137, 'P', 'N', 'G', 13, 10, 26, 10 };
        fwrite(sig, 1, 8, f);

        uint8_t ihdr[13] = {
                w >> 24, w >> 16, w >> 8, w,
                h >> 24, h >> 16, h >> 8, h,
                8, 2, 0, 0, 0,   // 8-bit, colour type 2 (RGB), deflate, no filter/interlace
        };
        sshot_chunk(f, "IHDR", ihdr, sizeof ihdr);

        // raw image: each row is a filter byte (0) followed by w*3 colour bytes
        size_t stride = (size_t)w * 3 + 1;
        size_t raw_len = stride * h;
        uint8_t *raw = malloc(raw_len);
        if (!raw) { fclose(f); return -1; }
        for (uint32_t y = 0; y < h; y++) {
                raw[y * stride] = 0;
                memcpy(raw + y * stride + 1, rgb + (size_t)y * w * 3, (size_t)w * 3);
        }

        // zlib stream: 2-byte header + stored DEFLATE blocks (<=65535 each) + adler32
        size_t nblocks = (raw_len + 65534) / 65535;
        if (nblocks == 0) nblocks = 1;
        size_t zlen = 2 + raw_len + nblocks * 5 + 4;
        uint8_t *z = malloc(zlen);
        if (!z) { free(raw); fclose(f); return -1; }
        uint8_t *zp = z;
        *zp++ = 0x78; *zp++ = 0x01;              // CMF/FLG (no preset dict, fastest)
        size_t off = 0;
        while (off < raw_len) {
                size_t n = raw_len - off;
                if (n > 65535) n = 65535;
                *zp++ = (off + n >= raw_len) ? 1 : 0; // BFINAL on the last block
                *zp++ = n & 0xff; *zp++ = (n >> 8) & 0xff;
                uint16_t nn = ~(uint16_t)n;
                *zp++ = nn & 0xff; *zp++ = (nn >> 8) & 0xff;
                memcpy(zp, raw + off, n);
                zp += n;
                off += n;
        }
        // adler-32 of the raw (filtered) data
        uint32_t a = 1, b = 0;
        for (size_t i = 0; i < raw_len; i++) {
                a = (a + raw[i]) % 65521;
                b = (b + a) % 65521;
        }
        uint32_t adler = (b << 16) | a;
        *zp++ = adler >> 24; *zp++ = adler >> 16; *zp++ = adler >> 8; *zp++ = adler;

        sshot_chunk(f, "IDAT", z, (uint32_t)(zp - z));
        sshot_chunk(f, "IEND", NULL, 0);

        free(z);
        free(raw);
        fclose(f);
        return 0;
}

// Copy the last presented swapchain image to the CPU and save it as a PNG.
// Meant to be called from the main loop (e.g. a debug socket command) between
// frames, not while a frame is mid-record. Returns 0 on success.
static int sshot_capture(VkImage src, const char *path)
{
        uint32_t w = vk.bestSwapchainExtent.width;
        uint32_t h = vk.bestSwapchainExtent.height;
        VkFormat fmt = vk.bestSurfaceFormat.format;
        VkDeviceSize bufsize = (VkDeviceSize)w * h * 4;

        // host-visible buffer to receive the copied pixels
        VkBuffer buf;
        VkBufferCreateInfo bufInfo = {
                .sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
                .size = bufsize,
                .usage = VK_BUFFER_USAGE_TRANSFER_DST_BIT,
                .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
        };
        if (vkCreateBuffer(vk.device, &bufInfo, NULL, &buf) != VK_SUCCESS)
                return -1;

        VkMemoryRequirements memReq;
        vkGetBufferMemoryRequirements(vk.device, buf, &memReq);
        VkPhysicalDeviceMemoryProperties memProps;
        vkGetPhysicalDeviceMemoryProperties(*vk.bestPhysicalDevice, &memProps);
        uint32_t memType = UINT32_MAX;
        VkMemoryPropertyFlags wantmem = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
                                        VK_MEMORY_PROPERTY_HOST_COHERENT_BIT;
        for (uint32_t i = 0; i < memProps.memoryTypeCount; i++)
                if ((memReq.memoryTypeBits & (1u << i)) &&
                    (memProps.memoryTypes[i].propertyFlags & wantmem) == wantmem) {
                        memType = i;
                        break;
                }
        if (memType == UINT32_MAX) {
                vkDestroyBuffer(vk.device, buf, NULL);
                return -1;
        }

        VkDeviceMemory mem;
        VkMemoryAllocateInfo allocInfo = {
                .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
                .allocationSize = memReq.size,
                .memoryTypeIndex = memType,
        };
        vkAllocateMemory(vk.device, &allocInfo, NULL, &mem);
        vkBindBufferMemory(vk.device, buf, mem, 0);

        // one-shot command buffer: present-src -> transfer-src, copy, back again
        VkCommandBuffer cmd;
        VkCommandBufferAllocateInfo cmdAlloc = {
                .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO,
                .commandPool = vk.commandPool,
                .level = VK_COMMAND_BUFFER_LEVEL_PRIMARY,
                .commandBufferCount = 1,
        };
        vkAllocateCommandBuffers(vk.device, &cmdAlloc, &cmd);
        VkCommandBufferBeginInfo begin = {
                .sType = VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO,
                .flags = VK_COMMAND_BUFFER_USAGE_ONE_TIME_SUBMIT_BIT,
        };
        vkBeginCommandBuffer(cmd, &begin);

        VkImageMemoryBarrier toSrc = {
                .sType = VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER,
                .srcAccessMask = VK_ACCESS_MEMORY_READ_BIT,
                .dstAccessMask = VK_ACCESS_TRANSFER_READ_BIT,
                .oldLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR,
                .newLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                .srcQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
                .dstQueueFamilyIndex = VK_QUEUE_FAMILY_IGNORED,
                .image = src,
                .subresourceRange = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 1, 0, 1 },
        };
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
                VK_PIPELINE_STAGE_TRANSFER_BIT, 0, 0, NULL, 0, NULL, 1, &toSrc);

        VkBufferImageCopy region = {
                .bufferOffset = 0,
                .bufferRowLength = 0,   // tightly packed
                .bufferImageHeight = 0,
                .imageSubresource = { VK_IMAGE_ASPECT_COLOR_BIT, 0, 0, 1 },
                .imageOffset = { 0, 0, 0 },
                .imageExtent = { w, h, 1 },
        };
        vkCmdCopyImageToBuffer(cmd, src, VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL,
                buf, 1, &region);

        VkImageMemoryBarrier toPresent = toSrc;
        toPresent.srcAccessMask = VK_ACCESS_TRANSFER_READ_BIT;
        toPresent.dstAccessMask = VK_ACCESS_MEMORY_READ_BIT;
        toPresent.oldLayout = VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL;
        toPresent.newLayout = VK_IMAGE_LAYOUT_PRESENT_SRC_KHR;
        vkCmdPipelineBarrier(cmd, VK_PIPELINE_STAGE_TRANSFER_BIT,
                VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT, 0, 0, NULL, 0, NULL, 1, &toPresent);

        vkEndCommandBuffer(cmd);

        VkFence fence;
        VkFenceCreateInfo fenceInfo = { .sType = VK_STRUCTURE_TYPE_FENCE_CREATE_INFO };
        vkCreateFence(vk.device, &fenceInfo, NULL, &fence);
        VkSubmitInfo submit = {
                .sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
                .commandBufferCount = 1,
                .pCommandBuffers = &cmd,
        };
        vkQueueSubmit(vk.drawingQueue, 1, &submit, fence);
        vkWaitForFences(vk.device, 1, &fence, VK_TRUE, UINT64_MAX);
        vkDestroyFence(vk.device, fence, NULL);
        vkFreeCommandBuffers(vk.device, vk.commandPool, 1, &cmd);

        // swizzle to RGB (swapchains are usually BGRA) and drop alpha
        void *mapped;
        vkMapMemory(vk.device, mem, 0, bufsize, 0, &mapped);
        int bgr = (fmt == VK_FORMAT_B8G8R8A8_UNORM || fmt == VK_FORMAT_B8G8R8A8_SRGB);
        uint8_t *rgb = malloc((size_t)w * h * 3);
        int rc = -1;
        if (rgb) {
                const uint8_t *px = mapped;
                for (size_t i = 0; i < (size_t)w * h; i++) {
                        const uint8_t *p = px + i * 4;
                        uint8_t *o = rgb + i * 3;
                        o[0] = bgr ? p[2] : p[0];
                        o[1] = p[1];
                        o[2] = bgr ? p[0] : p[2];
                }
                rc = sshot_write_png(path, rgb, w, h);
                free(rgb);
        }
        vkUnmapMemory(vk.device, mem);

        vkDestroyBuffer(vk.device, buf, NULL);
        vkFreeMemory(vk.device, mem, NULL);
        return rc;
}

// Ask for a PNG of the next rendered frame. The capture runs inside
// vulkan_submit while the image is still acquired (see sshot_capture), so the
// file lands a frame later - call it from the game loop, not mid-frame.
void vulkan_request_screenshot(const char *path)
{
        snprintf(sshot_pending_path, sizeof sshot_pending_path, "%s", path);
        sshot_pending = 1;
}

void vulkan_shutdown()
{
        vkDeviceWaitIdle(vk.device);
        deleteEmptyFences(&vk.backFences);
        deleteFences(&vk.device, &vk.frontFences, vk.maxFrames);
        deleteSemaphores(&vk.device, &vk.signalSemaphores, vk.swapchainImageCount);
        deleteSemaphores(&vk.device, &vk.waitSemaphores, vk.maxFrames);
        deleteCommandBuffers(&vk.device, vk.commandBuffers, &vk.commandPool, vk.swapchainImageCount);
        deleteCommandPool(&vk.device, &vk.commandPool);
        while (--vk.pipelineCount >= 0)
        {
                deleteGraphicsPipeline(&vk.device, &vk.pipelines[vk.pipelineCount].pipeline);
                deletePipelineLayout(&vk.device, &vk.pipelines[vk.pipelineCount].layout);
        }
        vulkan_destroy_swapchain();
        deleteRenderPass(&vk.device, &vk.renderPass);
        deleteSurface(&vk.surface, &vk.instance);
        deleteWindow(vk.window);
        deleteDevice(&vk.device);
        deletePhysicalDevices(&vk.physicalDevices);
        deleteInstance(&vk.instance);
}

void myDrawCallback(VkCommandBuffer cmdbuf)
{
        vkCmdBindPipeline(cmdbuf, VK_PIPELINE_BIND_POINT_GRAPHICS, vk.pipelines[0].pipeline);

        VkViewport viewport = { 0, 0, vk.bestSwapchainExtent.width, vk.bestSwapchainExtent.height, 0, 1 };
        VkRect2D scissor = { {0, 0}, {vk.bestSwapchainExtent.width, vk.bestSwapchainExtent.height} };
        vkCmdSetViewport(cmdbuf, 0, 1, &viewport);
        vkCmdSetScissor(cmdbuf, 0, 1, &scissor);

        vkCmdDraw(cmdbuf, 3, 1, 0, 0);
}

#ifdef TINYC_VULKAN_TRIANGLE_MAIN
int main()
{
        vulkan_startup("TinyC.Games Vulkan test", "../assets/tinyc-icon.png", "./shaders/", 1440, 900);
        int pipe = vulkan_make_pipeline(
                "triangle.vert",
                "triangle.geom",
                "triangle.frag",
                0, NULL, 0, NULL, NULL, VK_NULL_HANDLE, 0
        );

        SDL_Event event;
        bool running = true;

        while (running) {
                while (SDL_PollEvent(&event)) {
                        if (event.type == SDL_EVENT_QUIT)
                                running = false;
                }
                vulkan_acquire_next();
                myDrawCallback(vk.commandBuffers[vk.imageIndex]);
                vulkan_submit();
        }

        vulkan_shutdown();
}
#endif

#endif //VULKAN_DEMO_MAIN_C
