#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#define TINYC_DIR ".."
#include "build-config.h" // generated by CMake from build-config.h.in

#define SDL_DISABLE_IMMINTRIN_H
#include <SDL3/SDL.h>
#include <SDL3/SDL_main.h>
#include <SDL3/SDL_vulkan.h>
#include "../common/tinyc.games/vulkan/main.c"

#define STBI_NO_SIMD
#define STB_IMAGE_IMPLEMENTATION
#include "../common/nothings/stb_image.h"

#define WINSZ 1200

int win_x = WINSZ;
int win_y = WINSZ;

SDL_Event event;
SDL_Window *win;

void setup();

#include "timer.c"
#include "../common/tinyc.games/utils.c"
#include "../common/tinyc.games/terrain.c"

#define VBUFLEN (WINSZ * 5)

int main_pipe;
VkBuffer vbuf_gpu;
VkDeviceMemory vbuf_gpu_memory;
char *vbuf_mapped;
float vbuf[VBUFLEN];
int vbuf_n;
int points_total; // points uploaded to the GPU so far

void draw_setup()
{
        VkVertexInputBindingDescription bindingDesc = {
                .binding = 0,
                .stride = 5 * sizeof(float),
                .inputRate = VK_VERTEX_INPUT_RATE_VERTEX,
        };
        VkVertexInputAttributeDescription attributeDescs[] = {
                {.location = 0, .binding = 0, .format = VK_FORMAT_R32G32_SFLOAT, .offset = 0},
                {.location = 1, .binding = 0, .format = VK_FORMAT_R32G32B32_SFLOAT, .offset = 2 * sizeof(float)},
        };
        main_pipe = vulkan_make_pipeline("noise.vert", NULL, "noise.frag",
                1, &bindingDesc, 2, attributeDescs, NULL, VK_NULL_HANDLE,
                PIPE_NO_DEPTH_TEST | PIPE_NO_CULL | PIPE_POINTS);

        // one buffer big enough for every point on screen; columns are
        // appended as they are computed and never modified after upload,
        // so frames in flight never see a partial write
        VkBufferCreateInfo buf_info = {
                .sType = VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO,
                .size = (VkDeviceSize)WINSZ * VBUFLEN * sizeof(float),
                .usage = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT,
                .sharingMode = VK_SHARING_MODE_EXCLUSIVE,
        };
        vkCreateBuffer(vk.device, &buf_info, NULL, &vbuf_gpu);

        VkMemoryRequirements mem_reqs;
        vkGetBufferMemoryRequirements(vk.device, vbuf_gpu, &mem_reqs);

        VkPhysicalDeviceMemoryProperties mem_props;
        vkGetPhysicalDeviceMemoryProperties(*vk.bestPhysicalDevice, &mem_props);
        uint32_t mem_type = 0;
        VkMemoryPropertyFlags wanted = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT;
        for (uint32_t i = 0; i < mem_props.memoryTypeCount; i++)
                if ((mem_reqs.memoryTypeBits & (1 << i)) &&
                                (mem_props.memoryTypes[i].propertyFlags & wanted) == wanted)
                {
                        mem_type = i;
                        break;
                }

        VkMemoryAllocateInfo alloc_info = {
                .sType = VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO,
                .allocationSize = mem_reqs.size,
                .memoryTypeIndex = mem_type,
        };
        vkAllocateMemory(vk.device, &alloc_info, NULL, &vbuf_gpu_memory);
        vkBindBufferMemory(vk.device, vbuf_gpu, vbuf_gpu_memory, 0);
        vkMapMemory(vk.device, vbuf_gpu_memory, 0, buf_info.size, 0, (void **)&vbuf_mapped);
}

void vertex(float x, float y, float r, float g, float b)
{
        if (vbuf_n >= VBUFLEN - 5) return;
        vbuf[vbuf_n++] = x;
        vbuf[vbuf_n++] = y;
        vbuf[vbuf_n++] = r;
        vbuf[vbuf_n++] = g;
        vbuf[vbuf_n++] = b;
}

int x;

void create_verts()
{
        for (int y = 0; y < WINSZ; y++)
        {
                float h = get_filtered_height(x, y);

                #ifndef BLACK_AND_WHITE
                #define BLACK_AND_WHITE 0
                #endif
                if (BLACK_AND_WHITE) // black and white
                {
                        h = remap(h, 0.f, 1.f, -1.f, 2.f);
                        vertex(x, y, h, h, h);
                }
                else if (h > .7f)
                {
                        h = remap(h, .7f, 1.f, 1.f, 0.f);
                        vertex(x, y, 1.f, h, 1.f);
                }
                else if (h > .6f)
                {
                        h = remap(h, .6f, .7f, 0.f, 1.f);
                        vertex(x, y, h, 1.f, h);
                }
                else if (h > .51f)
                {
                        vertex(x, y, 0, remap(h, .51f, .6f, .4f, 1.f), 0);
                }
                else if (h > .49f)
                {
                        h = remap(h, .49f, .51f, .9f, .5f);
                        vertex(x, y, h, h, h * .2f);
                }
                else if (h > .3f)
                {
                        vertex(x, y, 0, 0, remap(h, .3f, .49f, 0.f, 1.f));
                }
                else
                {
                        vertex(x, y, remap(h, 0.f, .3f, 1.f, 0.f), 0, 0);
                }
        }

        if (++x == WINSZ)
        {
                char timings_buf[8000];
                timer_print(timings_buf, 8000, true);
                fprintf(stderr, "%s\n"
                                "     noise(): hits   = %10d\n"
                                "              misses = %10d\n"
                                "get_height(): hits   = %10d\n"
                                "              misses = %10d\n",
                                timings_buf, noise_hit, noise_miss, get_height_hit, get_height_miss);
        }
}

// append the freshly computed column to the GPU buffer
void upload_verts()
{
        memcpy(vbuf_mapped + (size_t)points_total * 5 * sizeof(float), vbuf, vbuf_n * sizeof(float));
        points_total += vbuf_n / 5;
        vbuf_n = 0;
}

// draw all points computed so far
void draw_verts()
{
        VkCommandBuffer cmd = vk.commandBuffers[vk.imageIndex];
        vkCmdBindPipeline(cmd, VK_PIPELINE_BIND_POINT_GRAPHICS, vk.pipelines[main_pipe].pipeline);

        VkViewport viewport = { 0, 0, vk.bestSwapchainExtent.width, vk.bestSwapchainExtent.height, 0, 1 };
        VkRect2D scissor = { {0, 0}, {vk.bestSwapchainExtent.width, vk.bestSwapchainExtent.height} };
        vkCmdSetViewport(cmd, 0, 1, &viewport);
        vkCmdSetScissor(cmd, 0, 1, &scissor);

        // pixel coords to Vulkan clip space, origin top-left, Y down
        float ortho[16] = {
                2.f / win_x, 0, 0, 0,
                0, 2.f / win_y, 0, 0,
                0, 0, 1, 0,
               -1, -1, 0, 1,
        };
        vkCmdPushConstants(cmd, vk.pipelines[main_pipe].layout,
                VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
                0, sizeof ortho, ortho);

        VkDeviceSize vb_offset = 0;
        vkCmdBindVertexBuffers(cmd, 0, 1, &vbuf_gpu, &vb_offset);
        vkCmdDraw(cmd, points_total, 1, 0, 0);
}

// the entry point and main game loop
int main()
{
        setup();
        for (;;)
        {
                while (SDL_PollEvent(&event)) switch (event.type)
                {
                        case SDL_EVENT_KEY_DOWN:
                                x = 0;
                                world_seed++;
                                points_total = 0;
                                // frames in flight may still read the old points
                                vkDeviceWaitIdle(vk.device);
                                break;
                        case SDL_EVENT_QUIT:
                                exit(0);
                        case SDL_EVENT_WINDOW_PIXEL_SIZE_CHANGED:
                                vulkan_recreate_swapchain();
                                SDL_GetWindowSizeInPixels(win, &win_x, &win_y);
                                break;
                }

                if (x == WINSZ)
                {
                        TIMECALL(SDL_Delay, (10));
                }
                else
                {
                        TIMECALL(create_verts, ());
                        TIMECALL(upload_verts, ());
                }
                TIMECALL(vulkan_acquire_next, ());
                TIMECALL(draw_verts, ());
                TIMECALL(vulkan_submit, ());
        }
}

// initial setup to get the window and rendering going
void setup()
{
        srand(time(NULL));
        world_seed = 103; //rand();

        SDL_Init(SDL_INIT_VIDEO);

        vulkan_startup("Taylor Noise Test", TINYC_DIR "/common/tinyc.games/vulkan/assets/tinyc-icon.png",
                        TINYC_DIR "/noise-demo/shaders/", win_x, win_y);
        win = vk.window;
        vk.clear_color = (VkClearColorValue){{0.5f, 0.5f, 0.5f, 1.f}};

        SDL_GetWindowSizeInPixels(win, &win_x, &win_y);
        draw_setup();
        noise_setup();
}
